language: java
sudo: true

jdk:
- oraclejdk8
#- openjdk7

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true


after_success:
- mvn clean test cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report