language: java
sudo: false

jdk:
- oraclejdk8
#- openjdk7

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


after_success:
- mvn clean test cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report